blank_issues_enabled: false
contact_links:
  - name: ğŸš€ GitHub Discussions
    url: https://github.com/hi-tomato/barogo/discussions
    about: ì¼ë°˜ì ì¸ í† ë¡ ì´ë‚˜ ì•„ì´ë””ì–´ ê³µìœ ëŠ” Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”!
